### ISSUE TITLE
Create conversion guides

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/editor-guide#1]
@metanorma/editors we would like to create some conversion guides based on your best practices.

There are generally two types of conversions:

* from Word
* from PDFs

Can you help create editing guides + tips + FAQ for these workflows in this repo?

Thanks!

**Comment by manuel489** [comment]
@ronaldtse , would the conversion guide go in a new .adoc file or in the existing README.adoc?

**Comment by ronaldtse** [comment]
@manuel489 let's make it into new .adoc? Eventually we want to provide these guides on metanorma.com!

**Comment by manuel489** [comment]
Changes are merged. Closing.
